version: '3'
services:
  db:
    container_name: argssearch-db
    image: postgres:latest
    environment:
      - POSTGRES_USER=irargdb
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=argdb

    ports:
      - "5432:5432"
  app:
    container_name: arggsearch-app
    image: argssearch
    links:
      - db
    depends_on:
      - db