package argssearch.shared.nlp;

public enum EntityType {
    MONEY, DATA, NUMBER,
    TITLE, DATE, ORDINAL,
    CAUSE_OF_DEATH, PERCENT,
    URL, MISC, ORGANIZATION,
    DURATION, COUNTRY, CRIMINAL_CHARGE,
    STATE_OR_PROVINCE, RELIGION, TIME,
    PERSON
}
