DROP TABLE IF EXISTS arg_index;
DROP TABLE IF EXISTS premise_index;
DROP TABLE IF EXISTS discussion_index;
DROP TABLE IF EXISTS token;
DROP TABLE IF EXISTS argument;
DROP TABLE IF EXISTS premise;
DROP TABLE IF EXISTS discussion;
DROP TABLE IF EXISTS source;

DROP TYPE IF EXISTS class;